### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by shreyash14s** [Kjuly/pngcrush#3]
When I run the `batch_script.sh` I get some junk output below

    ../pngcrush/pngcrush: 1: ../pngcrush/pngcrush: �������: not found
    ../pngcrush/pngcrush: 2: ../pngcrush/pngcrush: dK�: not found
    ../pngcrush/pngcrush: 3: ../pngcrush/pngcrush: �__stubs__TEXTVV�__stub_helper__TEXT0W�0W�__const__TEXT: not found
    ../pngcrush/pngcrush: 4: ../pngcrush/pngcrush: Syntax error: word unexpected (expecting ")")

And when I try running the executable directly it give error 

    bash: ./pngcrush/pngcrush: cannot execute binary file: Exec format error

**Comment by Kjuly** [comment]
> bash: ./pngcrush/pngcrush: cannot execute binary file: Exec format error

Guess u attempt to run on a 32-bit platform, if so, u need to recompile it w/ [cmake][1] (the existing one was compiled under 64-bit platform).

> ../pngcrush/pngcrush: 1: ../pngcrush/pngcrush: �����������: not found
> ...

If u still get this error after having recompiled the binary, guess the file name not recognised, plz try it w/ english instead.  

(Btw, in case u'r under Windows platform, plz try `cmd_script.cmd` instead of `batch_script.sh`.  )

  [1]: https://cmake.org

**Comment by shreyash14s** [comment]
Thanks for the reply.

You are right about recompiling part. I recompiled it using `make`.

    make clean
    make

Doing these do commands in `pngcrush` directory worked.

I don't know why the executable didn't work. I am on Ubuntu 16.04 64-bit machine. Also I had only one file `abc.png` in `workspace_in` directory.

**Comment by shreyash14s** [comment]
@Kjuly It would be better if the command to build the executable were there in README file. 

And I don't think we need those unneccessary `.o` file.

**Comment by Kjuly** [comment]
Good suggestion, but this repo's main purpose is handling batch job, that's why it's compiled already, generally, it will work w/o any problem, but when get issue like ur case, can just recompile it. As i already point it out in README.

> __Note__: The binary files under `./pngcrush/` were built by "GNU Make" (v3.81), you can build by yourself if want.

I'll extend the README w/ build process, thanks for ur feedback :)
